FROM cimg/base:current

# cimg/base already has: curl, git, docker, jq, etc.
# Only add things that AREN'T in cimg/base:

RUN sudo apt-get update && sudo apt-get install -y \
    libmariadb-dev \
    libmariadb-dev-compat \
    libmagic-dev

USER circleci
WORKDIR /home/circleci/project